tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOTexport AWS_ACCESS_KEY_ID=" AKIASP4VKML662P3CXBP
"
export AWS_SECRET_ACCESS_KEY=" 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
"
export AWS_DEFAULT_REGION=us-east-1

vscode:
  extensions:
    - 42Crunch.vscode-openapi